name: Default

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: gofmt
        run: |
          gofmt -w -l $(find . -name '*.go')

      - name: Install tools
        run: make install

      - name: Assets
        run: make assets

      - name: Porcelain
        run: |
          go mod tidy
          test -z "$(git status --porcelain)" || (git status; git diff; false)

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: make test

  build-ui:
    name: Build UI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: make install-ui

      - name: Build
        run: make ui

      - name: Lint
        run: make lint-ui

      - name: Test
        run: make test-ui

      - name: Porcelain
        run: |
          test -z "$(git status --porcelain)" || (git status; git diff; false)
